# Generated by Django 5.1.6 on 2025-06-02 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_submitted'],
            },
        ),
        migrations.DeleteModel(
            name='ContactSubmission',
        ),
        migrations.DeleteModel(
            name='SitePage',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-completion_date']},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='projecttechnology',
            options={'verbose_name_plural': 'Project Technologies'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['name'], 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='testimonial',
            old_name='created_at',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='projectimage',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='service',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='service',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='category',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='technology',
            name='proficiency_level',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='date_received',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='display_order',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='is_visible',
        ),
        migrations.AddField(
            model_name='project',
            name='live_url',
            field=models.URLField(blank=True, null=True, verbose_name='Live Demo URL'),
        ),
        migrations.AddField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which images appear.'),
        ),
        migrations.AddField(
            model_name='technology',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='full_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Check to display on the homepage.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='repository_url',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub/Repo URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Descriptive text for accessibility.', max_length=255),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='caption',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to='project_images/'),
        ),
        migrations.AlterField(
            model_name='projecttechnology',
            name='usage_context',
            field=models.CharField(blank=True, help_text="How this technology was used in the project (e.g., 'Frontend UI', 'Backend API').", max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Font Awesome icon class (e.g., 'fas fa-laptop-code')", max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='technology',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='technology_logos/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_company_or_role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='client_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote_text',
            field=models.TextField(),
        ),
    ]
